### ISSUE TITLE
[META] Add issue tags to github repo

### ISSUE THREAD

**Issue by ethanchristensen01** [calvinloveland/operationalize#13]
Tags could be "Feature Request", "Bug", "Meta", etc.

**Comment by ethanchristensen01** [comment]
I realized that github already has issue tags. A way for reporters to specify a label would be ideal though.

Maybe that requires certain permissions though?

**Comment by calvinloveland** [comment]
Bleh I don't like being tied to github for issue management. I'm gonna try and manage it with a TODO.txt we'll see if that works. todos can have tags using +tag format
